config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :cards
  end 
  
  get '/' => 'home#home', as: :home

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/allcards' => 'cards#allcards', as: :all_cards
  get '/assigncards' => 'cards#assigncards', as: :assign_cards
  get '/unshare' => 'cards#unshare', as: :unshare_card
  get '/sharecard/:id' => 'cards#share'
  post '/sharecard/:id' => 'cards#complete_share', as: :share_card

end

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :users, :through => :user_shared_cards
	has_many :user_shared_cards

	months = [
		'Jan','Feb','Mar',
		'Apr','May','Jun',
		'Jul','Aug','Sep',
		'Oct','Nov','Dec'
	]

	validates_presence_of :balance
	validates_presence_of :number
	validates :expire_month, presence: true, length: {maximum: 2}
	validates :expire_year, presence: true, length: {maximum: 4}

	before_save :autofill_card_type

	# Determine the card type/bank from the first few digits
	#  of the submitted digits; assumed to be a CC # with
	# no whitespace
	#
	def autofill_card_type

		# get the card number
		#
		digits = self.number.to_s
		type = "unknown"
		#
		# check the credit card digits against known card types
		#
		if digits =~ /^4[0-9]{6,}$/ # Visa cards start with 4
			type = "VISA"
		elsif digits =~ /^5[1-5][0-9]{5,}$/ 
			# Mastercard CREDIT cards start with the digitss 51 through 55,
			# there are other mastercard types this will not detect
			#
			type = "MASTERCARD"
		elsif digits =~ /^3[47][0-9]{5,}$/ # AMEX starts with 34 or 37
			type = "AMEX"
		elsif digits =~ /^3(?:0[0-5]|[68][0-9])[0-9]{4,}$/ 
			# Diners Club card digitss begin with 300 through 305, 36 or 38.
			# there are other dinersclub cards with different characteristics,
			# I'm ignoring those for this exercise
			#
			type = "DINERSCLUB"
		elsif digits =~ /^6(?:011|5[0-9]{2})[0-9]{3,}$/
			# 
			# Discover card digitss begin with 6011 or 65.
			#
			type = "DISCOVER"
		elsif digits =~ /^(?:2131|1800|35[0-9]{3})[0-9]{3,}$/
			#
			# JCB cards begin with 2131, 1800 or 35.
			# 
			type = "JCB"
		else 
			# type - unknown?
			# flash error: "Card cannot be identified"
		end

		# set the card type
		#
		self.cardtype = type
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cards, :through => :user_shared_cards
	has_many :user_shared_cards

	validates :email, presence: true, uniqueness: true
	validates :password, confirmation: true, presence: true, length: {minimum: 4, maximum: 15}
	validates_presence_of :phone
	validates_presence_of :fname
	validates_presence_of :lname

end

app/models/user_shared_card.rb
class UserSharedCard < ActiveRecord::Base
	belongs_to :user
	belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	def current_user
		@current_user ||= User.find_by_id session[:user_id]
	end

	def logged_in_as user_id
		user == current_user
	end

	helper_method :current_user, :logged_in_as
end

app/controllers/cards_controller.rb
require 'pp'


class CardsController < ApplicationController
	# before_action :current_user
	def allcards
		@cards = Card.all
		if @cards.present?
			flash.now[:notice] = "Cards display successfully."
		else
			flash.now[:alert] = "Sorry, there are no cards to display."
		end
	end
	def complete_share
		user_email = params[:user_email].strip
		user = User.find_by_email user_email	
		card = Card.find params[:id]
		if user && card
			user.cards << card
			flash.now[:notice] = "Card shared successfully."
		else
			flash.now[:alert] = "There was a problem sharing the Card. Please verify user email."
		end
		redirect_to user_path user.id
	end
	def create
		@card = Card.new(card_params)
		if @card.save
			@card.user_id = current_user.id
			# @card.users << current_user
			# @card.save
			redirect_to user_path current_user.id
		else 
			flash.now[:alert] = "Card not created, please try again."
			redirect_to new_user_card_path(current_user.id)
		end
	end
	def destroy
		card = Card.find_by_id params[:id]

		if card.destroy
		 flash[:notice] = "Card deleted successfully."
		else
		 flash[:alert] = "There was a problem deleting the Card."
		end
		redirect_to user_path current_user.id
	end
	def new
		@card = Card.new
	end
	def share
		@card = Card.find_by_id params[:id]
		@users = User.all
	end
	def unshare
		user = User.find params[:user_id]
		card = Card.find params[:card_id]
		if user && card
			user.cards.delete(card)
			flash[:notice] = "Card unshared successfully."
		else
			flash[:alert] = "There was a problem sharing the Card. Please verify user email."
		end
		redirect_to user_path user.id
	end

	private
	def card_params
		params.require(:card).permit(:number, :expire_month, :expire_year, :balance, :cardtype, :user_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def new
	end
	def create
	end
	def destroy
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		@user = User.where(email: params[:email]).first
		if @user && @user.password == params[:password]
			session[:user_id] = @user.id
			current_user
			flash.now[:notice] = "You have logged in successfully."
			redirect_to '/'
		else 
			flash[:alert] = "invalid user name or email #{params[:email]}"
			redirect_to login_path
		end
	end

	#route for logging out a user
	def destroy
		session[:user_id] = nil
		flash[:notice] = "You have logged out."
		redirect_to '/'
	end

	#route for login form
	def new
		# no code needed here; all handled in the view
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
		if @users.present?
			flash[:notice] = "Users display successfully."
		else
			flash[:alert] = "Sorry, there were no users to display."
		end
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find_by_id params[:id]
		if current_user
			# @cards = @user.cards
			@cards = []
			@sharedCards = []
			allCards = Card.all
			allCards.each do |card|
				if card.user_id == current_user.id
					@cards << card 
					#
					# check if card is shared
					#
					shares = UserSharedCard.where(card_id: card.id)
					shares.each do |share|
						@sharedCards << share
					end
				end

			end
		end
	end 
	
	private
		def user_params
			params.require(:user).permit(:fname, :lname, :username, :password, :email)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/allcards.html.erb
<h1>All Cards</h1>

<% @cards.each do |card| %>   
	<p>
		<%= "#{card.cardtype} #{card.number} "%> 
		<%= link_to "Add Card To Your Acount", assign_cards_path(card_id: card.id, user_id: current_user) %>
		<%= link_to "Remove Card From Your Acount", unshare_card_path(card_id: card.id, user_id: current_user) %>
	</p>
	<%= link_to("Delete", user_card_path(current_user,card.id), method: :delete) %>
	<%= link_to "Edit", edit_user_card_path(current_user,card.id) %>
<% end %>
<hr>
<p>
	<%= link_to "Home", '/' %>
</p>
<p>
	<%= link_to "Sign up!", new_user_path %>
</p>
<h1>Users Should Be Listed Above</h1>

app/views/cards/create.html.erb
<h1>You have added a Card <%= "#{@card.cardtype}" %> </h1>

<%= link_to "User Page", user_path(current_user.id) %>

app/views/cards/new.html.erb
<h1>Add A New Card</h1>

<hr>

	<%= form_for @card, url: user_cards_path(current_user.id) do |f| %>
 	<p>
		<%=f.label "Card Number", { class: "numberFieldLabel" } %>
		<%=f.text_field :number, { class: "numberField" } %>
	</p><p>
		<%=f.label "Expiry Month (MM)", { class: "monthFieldLabel" } %>
		<%=f.text_field :expire_month, { class: "monthField" }  %>
		<%=f.label "Expiry Year (YYYY)", { class: "yearFieldLabel" } %>
		<%=f.text_field :expire_year, { class: "yearField" }  %>
	</p><p>
		<%=f.label "Balance", { class: "balanceFieldLabel" } %>
		<%=f.text_field :balance, { class: "balanceField" }  %>
	</p>

	<%=f.submit :create, { id: "linkGroup"} %> 
<% end %>

app/views/cards/share.html.erb
<h1>Share Card <%= "#{@card.id}" %> with another user!</h1>

<h3>Form for entering User email goes here</h3>

<%= form_tag share_card_path(@card.id), method: :post do %>
 	<p>
		<%=label_tag "Enter email the User you are sharing this card with: " %>
		<%=text_field_tag :user_email %>
	</p><p>
		<%= submit_tag :share %>
	<p>
<% end %>

<hr>
<% @users.each do |user| %>   
	<p>
		<%= "#{user.fname} #{user.lname} "%> 
		<%= link_to user.email, user %>
	</p>
<% end %>

app/views/home/home.html.erb
<h1>NYCDA MyWallet Exercise</h1>

<% if current_user %>
	<%= link_to "Logout", logout_path, method: :delete %>
<% else %>
	<%= link_to "Login", login_path %>
	<p>
		<%= link_to "Sign Up", new_user_path %>
	</p>
<% end %>


<%= link_to "Show Users", users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Wallet</title>
			<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.10/css/jquery.dataTables.css">
			<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.10/js/jquery.dataTables.js"></script>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="flash">
			<%= flash[:notice] if flash[:notice] %> 
			<%= flash[:alert] if flash[:alert] %>
		</div>
			
		<%= yield %>

	</body>
</html>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>   
	<p>
		<%= "#{user.fname} #{user.lname} "%> 
	
		<%= link_to user.email, user %>
	</p>
	<%= link_to("Delete", user_path(user.id), method: :delete) %>
	<!-- <%= link_to("Delete", user, method: :delete) %>	 -->
	<%= link_to "Edit", edit_user_path(user.id) %>
<% end %>
<hr>
<p>
	<%= link_to "Share Cards", all_cards_path %>
</p>
<p>
	<%= link_to "Home", '/' %>
</p>
<p>
	<%= link_to "Sign up!", new_user_path %>
</p>

app/views/users/new.html.erb
<h1>Sign-Up</h1>
<hr>

	<%= form_for @user do |f| %>
 	<p>
		<%=f.label "First Name", { class: "loginFieldLabel" } %>
		<%=f.text_field :fname, { class: "loginField" } %>
	</p><p>
		<%=f.label "Last Name", { class: "loginFieldLabel" } %>
		<%=f.text_field :lname, { class: "loginField" }  %>
		<%=f.label "Phone", { class: "loginFieldLabel" } %>
		<%=f.text_field :phone, { class: "loginField" }  %>
	</p><p>
		<%=f.label "Email", { class: "loginFieldLabel" } %>
		<%=f.text_field :email, { class: "loginField" }  %>
	</p>
		
	<p>
		<%=f.label "Password", { class: "loginFieldLabel" } %>
		<%=f.text_field :password, { class: "loginField" }  %>
		<%=f.label "Password", { class: "loginFieldLabel" } %>
		<%=f.text_field :password_confirmation, {class: "loginField" } %>
	</p>

	<%=f.submit :create, { id: "linkGroup"} %> 
<% end %>

app/views/users/show.html.erb
<h1><%= "#{@user.fname} #{@user.lname} Cards"%></h1>

<% if current_user %>
	<p>
		<%= link_to "Add A Card", new_user_card_path(current_user.id) %>
	</p>
<% end %>

<table id="UserCardTable" class="display">
	<thead>
		<tr>
			<th>Share Card</th>
			<th>Card Type</th>
			<th>Card Number</th>
			<th>Expires MM</th>
			<th>YYYY</th>
			<th>Balance</th> 
			<th>Delete Card</th>
		</tr>
	</thead>
	<tbody>
		<% if current_user %>
			<% if @cards %>
				<% balance = 0 %>
				<% @cards.each do |card| %>  
					<tr>
						<td><%= link_to "Share Card", "/sharecard/#{card.id}" %></td> 
						<td><%= card.cardtype %></td>
						<td><%= card.number %></td>
						<td><%= card.expire_month %></td>
						<td><%= card.expire_year %></td> 
						<td><%= card.balance%></td>
						<td><%= link_to "Remove Card", user_card_path(current_user.id, card.id), method: :delete %></td>
					</tr>
					<% balance += card.balance %>
				<% end %>
				<tr>
					<td></td> 
					<td></td>
					<td></td>
					<td></td>
					<td>Total Balance:</td> 
					<td><%= balance %></td>
					<td></td>
				</tr>
			<% else %>
				<h3>Please log in to view cards</h3>
			<% end %>
		<% end %>
	</tbody>
</table>
<hr>
<h2>Shared Cards</h2>
<table id="SharedCardTable" class="display">
	<thead>
		<tr>
			<th>Shared By</th>
			<th>Card Type</th>
			<th>Card Number</th>
			<th>Expires MM</th>
			<th>YYYY</th>
			<th>Balance</th> 
			<th>Unshare Card</th>
		</tr>
	</thead>
	<tbody>
		<% if current_user %>
			<% if @sharedCards %>
				<% @sharedCards.each do |scard| %>
				  	<% card = Card.find scard[:card_id] %>
				  	<% user = User.find scard[:user_id] %>
					<tr>
						<td><%= link_to "#{user.fname} #{user.lname}", user_path(user.id) %></td> 
						<td><%= card.cardtype %></td>
						<td><%= card.number %></td>
						<td><%= card.expire_month %></td>
						<td><%= card.expire_year %></td> 
						<td><%= card.balance%></td>
						<td><%= link_to "Unshare Card", unshare_card_path(card_id: scard[:card_id], user_id: scard[:user_id]) %></td> 
					</tr>
				<% end %>
			<% end %>
		<% end %>
	</tbody>
</table>